server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Agriculture?serverTimezone=Asia/Shanghai
    username: root
    password: 0213ljh!
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true